### ISSUE TITLE
Imgur unhandled expectation "?" in filename after extension.

### ISSUE THREAD

**Issue by NZBwhore** [nilfoer/gwaripper#5]
22:23:18 - CRITICAL - Uncaught exception:
Traceback (most recent call last):
  File "gwaripper-runner.py", line 23, in <module>
  File "cli.py", line 237, in main
  File "cli.py", line 293, in _cl_redditor
  File "cli.py", line 273, in download_all_subs
  File "gwaripper.py", line 256, in download_all
  File "gwaripper.py", line 171, in parse_and_download_submission
  File "gwaripper.py", line 262, in download
  File "gwaripper.py", line 426, in _download_collection
  File "gwaripper.py", line 304, in _download_file
  File "gwaripper.py", line 345, in _download_file_http
  File "download.py", line 107, in download_in_chunks
OSError: [Errno 22] Invalid argument: 

'C:\\filepath\\redditor\\filenamewiththefollowingextension -> ._1yp52c4.jpg?1'

[11736] Failed to execute script 'gwaripper-runner' due to unhandled exception!

Error apparent with kshib

**Comment by NZBwhore** [comment]
possible fix with os.rename, str.translate or re.sub?
Could help, but this py-newbie can't figure out where to put the code.

**Comment by omgitsmoe** [comment]
[602301a](https://github.com/nilfoer/gwaripper/commit/602301ac58317db4bc64aa47323865a2255c1bbc) should fix the issue

**Comment by nilfoer** [comment]
[602301a](https://github.com/nilfoer/gwaripper/commit/602301ac58317db4bc64aa47323865a2255c1bbc) should fix the issue.
